In [1]:
import gym
import numpy as np

## Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

## Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [4]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.404


In [5]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[2.91922816e-01 4.57077343e-03 7.13010523e-03 6.67879405e-03]
 [1.03977442e-03 3.58142180e-04 2.70072004e-04 1.84385894e-01]
 [1.60162592e-03 1.33450785e-03 1.50584012e-03 1.89335005e-01]
 [3.77826364e-04 1.06229570e-03 8.84943766e-04 6.75919157e-02]
 [3.48042887e-01 1.34237022e-05 1.04984472e-03 5.48688255e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.39966512e-02 1.16979828e-04 1.33874196e-03 5.63016276e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.42715858e-04 1.30356842e-03 5.55946363e-04 4.45436285e-01]
 [0.00000000e+00 2.33026771e-01 6.74862935e-04 5.94045262e-04]
 [1.26879732e-01 1.35792300e-04 4.98757738e-04 5.50707352e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.20879340e-04 0.00000000e+00 4.56300882e-01 4.99982757e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.46829375e-01]
 [0.00000000e+00 0.00000000e+00 0.

## Reference 
###### https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0